// GIT-USERS/Jerga/bwm-ng-new/src/app/manage/manage-rentals/manage-rentals.component.ts
import { Component, OnInit } from "@angular/core";
import { Rental } from "src/app/rental/shared/rental.model";
import { RentalService } from "src/app/rental/shared/rental.service";

@Component({
  selector: "bwm-manage-rentals",
  templateUrl: "./manage-rentals.component.html",
  styleUrls: ["./manage-rentals.component.scss"],
})
export class ManageRentalsComponent implements OnInit {
  rentals: Rental[];

  constructor(private rentalService: RentalService) {}

  ngOnInit() {
    this.rentalService.getAuthUserRentals().subscribe((rentals: Rental[]) => {
      this.rentals = rentals;
    });
  }

  deleteRental(rentalId: string) {
    const canDelete = this.askForPermission();
    if (!canDelete) {
      return;
    }

    this.rentalService.deleteRental(rentalId).subscribe(
      (_) => {
        const index = this.rentals.findIndex((r) => r._id === rentalId);
        this.rentals.splice(index, 1);

        alert("Rental has been deleted!");
      },
      (_) => alert("Rental cannot be deleted!")
    );
  }

  private askForPermission(): boolean {
    return window.confirm("Are you sure you want to delete rental?");
  }
}

<div class="bwm-list-page">
  <h1 class="title">My Rentals</h1>
  <div *ngIf="rentals" class="row">
    <div *ngFor="let rental of rentals" class="col-md-3 col-xs-12">
      <bwm-rental-card [rentalItem]="rental">
        <div class="button-container mt-1">
          <button (click)="deleteRental(rental._id)" class="btn btn-danger">
            Delete
          </button>
          <a
            class="btn bwm-btn-main ml-1"
            routerLink="/rentals/{{ rental._id }}/edit"
          >
            Edit
          </a>
        </div>
      </bwm-rental-card>
    </div>
    <div *ngIf="rentals.length === 0" class="alert alert-warning">
      No rentals created :(
    </div>
  </div>
</div>

// GIT-USERS/Jerga/bwm-react-new/src/pages/ManageRentals.js
import React from "react";
import { fetchUserRentals, deleteRental } from "actions";
import { connect } from "react-redux";
import RentalCard from "components/rental/RentalCard";
import ApiErrors from "components/forms/ApiErrors";
import { Link } from "react-router-dom";

class ManageRentals extends React.Component {
  componentDidMount() {
    this.props.dispatch(fetchUserRentals());
  }

  deleteRental = (rentalId) => {
    const canDelete = this.askForPermission();
    if (!canDelete) {
      return;
    }

    this.props.dispatch(deleteRental(rentalId));
  };

  askForPermission() {
    return window.confirm("Are you sure you want to delete this rental?");
  }

  renderRentals = (rentals) =>
    rentals.map((rental) => (
      <div key={rental._id} className="col-md-3">
        <RentalCard
          rental={rental}
          renderMenu={() => (
            <>
              <button
                onClick={() => this.deleteRental(rental._id)}
                className="btn btn-danger"
              >
                Delete
              </button>
              <Link
                to={{ pathname: `/rentals/${rental._id}/edit` }}
                className="btn btn-bwm-main ml-2"
              >
                Update
              </Link>
            </>
          )}
        />
      </div>
    ));

  render() {
    const { rentals, errors, isFetching } = this.props;
    return (
      <div className="card-list">
        <h1 className="page-title">My Rentals</h1>
        <ApiErrors errors={errors} />
        <div className="row">{this.renderRentals(rentals)}</div>
        {!isFetching && rentals.length === 0 && (
          <p className="alert alert-warning">
            You dont have any rentals currently created :(
          </p>
        )}
      </div>
    );
  }
}

const mapStateToProps = ({ manage }) => {
  return {
    rentals: manage.rentals.items,
    isFetching: manage.rentals.isFetching,
    errors: manage.rentals.errors,
  };
};

export default connect(mapStateToProps)(ManageRentals);
