// GIT-USERS/Jerga/book-with-me-ng/src/app/register/register.component.ts
import { Component, OnInit } from "@angular/core";
import { User, userFactory } from "../user/shared/user.model";
import { UserService } from "../user/shared/user.service";
import { Router } from "@angular/router";

@Component({
  selector: "bwm-register",
  templateUrl: "./register.component.html",
  styleUrls: ["./register.component.scss"],
})
export class RegisterComponent implements OnInit {
  public user: User;
  public errors = [];

  constructor(private userService: UserService, private router: Router) {}

  ngOnInit() {
    this.user = userFactory();
  }

  register() {
    this.userService.register(this.user).subscribe(
      (data) => {
        this.router.navigate(["/login", { M: "REGISTERED" }]);
      },
      (invalidResponse: any) => {
        this.errors = invalidResponse.error.errors;
      }
    );
  }
}

<section id="register">
  <div class="bwm-form">
    <div class="row">
      <div class="col-md-5">
        <h1 class="page-title">Register</h1>
        <form #registerForm="ngForm">
          <div class="form-group">
            <label for="username">Username</label>
            <input
              [(ngModel)]="user.username"
              name="username"
              type="text"
              class="form-control"
              id="username"
              required
              #username="ngModel"
            />
            <div
              class="alert alert-danger"
              *ngIf="
                username.invalid &&
                (username.dirty || username.touched) &&
                username.errors.required
              "
            >
              Name is required.
            </div>
          </div>

          <div class="form-group">
            <label for="email">Email</label>
            <input
              [(ngModel)]="user.email"
              name="email"
              type="email"
              class="form-control"
              id="email"
            />
          </div>

          <div class="form-group">
            <label for="password">Password</label>
            <input
              [(ngModel)]="user.password"
              name="password"
              type="password"
              class="form-control"
              id="password"
            />
          </div>

          <div class="form-group">
            <label for="passwordConfirmation">Confirm Password</label>
            <input
              [(ngModel)]="user.passwordConfirmation"
              name="passwordConfirmation"
              type="password"
              class="form-control"
              id="passwordConfirmation"
            />
          </div>
          <button
            [disabled]="!registerForm.form.valid"
            (click)="register()"
            type="submit"
            class="btn btn-bwm"
          >
            Submit
          </button>
        </form>
        <div *ngIf="errors.length > 0" class="alert alert-danger">
          <p *ngFor="let error of errors">
            {{ error.detail }}
          </p>
        </div>
      </div>
      <div class="col-md-6 ml-auto">
        <div class="image-container">
          <h2 class="catchphrase">
            As our member you have access to most awesome places in the world.
          </h2>
          <img src="assets/images/register-image.jpg" alt="" />
        </div>
      </div>
    </div>
  </div>
</section>

// GIT-USERS/Jerga/bwm-react-new/src/pages/Register.js
import React from "react";
import RegisterForm from "components/forms/RegisterForm";
import { registerUser } from "actions";
import { Redirect } from "react-router-dom";
import ApiErrors from "components/forms/ApiErrors";

class Register extends React.Component {
  state = {
    shouldRedirect: false,
    errors: [],
  };

  signUp = (registerData) => {
    registerUser(registerData)
      .then(() => this.setState({ shouldRedirect: true }))
      .catch((errors) => this.setState({ errors }));
  };

  render() {
    const { shouldRedirect, errors } = this.state;

    if (shouldRedirect) {
      return (
        <Redirect
          to={{
            pathname: "/login",
            state: { message: "You have been succesfuly registered!" },
          }}
        />
      );
    }

    return (
      <div className="bwm-form">
        <div className="row">
          <div className="col-md-5">
            <h1 className="page-title">Register</h1>
            <RegisterForm onSubmit={this.signUp} />
            <ApiErrors errors={errors} />
          </div>
          <div className="col-md-6 ml-auto">
            <div className="image-container">
              <h2 className="catchphrase">
                As our member you have access to most awesome places in the
                world.
              </h2>
              <img src="/images/register-image.jpg" alt="Register an user" />
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default Register;
