// GIT-USERS/Jerga/book-with-me-ng/src/app/login/login.component.ts
import { Component, OnInit } from "@angular/core";
import { UserService } from "../user/shared/user.service";
import { ActivatedRoute, Router } from "@angular/router";
import { LoginData } from "../user/shared/user.service";
import { MESSAGES } from "../shared/message-types";

@Component({
  selector: "bwm-login",
  templateUrl: "./login.component.html",
  styleUrls: ["./login.component.scss"],
})
export class LoginComponent implements OnInit {
  public loginData: LoginData = {
    email: "",
    password: "",
  };

  public errors: any = [];

  public notifyMessage: string = "";

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private auth: UserService
  ) {}

  ngOnInit() {
    this.route.params.subscribe((params) => {
      if (params["M"]) {
        this.notifyMessage = MESSAGES[params["M"]];
      }
    });
  }

  login(data) {
    this.auth.login(this.loginData).subscribe(
      (data) => {
        this.router.navigate(["/"]);
      },
      (invalidResponse: any) => {
        this.errors = invalidResponse.error.errors;
      }
    );
  }
}

<section id="login">
  <div class="bwm-form">
    <div class="row">
      <div class="col-md-5">
        <h1 class="page-title">Login</h1>
        <div *ngIf="notifyMessage" class="alert alert-success">
          <p>{{ notifyMessage }}</p>
        </div>
        <form (ngSubmit)="login(loginForm)" #loginForm="ngForm">
          <div class="form-group">
            <label for="email">Email</label>
            <input
              #email="ngModel"
              [(ngModel)]="loginData.email"
              type="email"
              name="email"
              class="form-control"
              id="email"
              required
              pattern="^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$"
            />
            <div
              class="alert alert-danger"
              *ngIf="
                email.invalid &&
                (email.dirty || email.touched) &&
                email.errors.pattern
              "
            >
              Invalid Email.
            </div>
          </div>

          <div class="form-group">
            <label for="password">Password</label>
            <input
              [(ngModel)]="loginData.password"
              type="password"
              name="password"
              class="form-control"
              id="password"
              required
            />
          </div>
          <button
            [disabled]="!loginForm.form.valid"
            type="submit"
            class="btn btn-bwm"
          >
            Submit
          </button>
        </form>
        <div *ngIf="errors.length > 0" class="alert alert-danger">
          <p *ngFor="let error of errors">
            {{ error.detail }}
          </p>
        </div>
      </div>
      <div class="col-md-6 ml-auto">
        <div class="image-container">
          <h2 class="catchphrase">
            Hundreds of awesome places in reach of few clicks.
          </h2>
          <img src="assets/images/login-image.jpg" alt="" />
        </div>
      </div>
    </div>
  </div>
</section>

// GIT-USERS/Jerga/bwm-new-react-github/src/pages/Login.js
import React from "react";
import LoginForm from "components/forms/LoginForm";
import { Redirect } from "react-router-dom";
import ApiErrors from "components/forms/ApiErrors";
import { withAuth } from "providers/AuthProvider";

class Login extends React.Component {
  state = {
    shouldRedirect: false,
    errors: [],
  };

  signIn = (loginData) => {
    this.props.auth
      .signIn(loginData)
      .then((_) => this.setState({ shouldRedirect: true }))
      .catch((errors) => this.setState({ errors }));
  };

  render() {
    const { errors, shouldRedirect } = this.state;
    const { message } = this.props.location.state || "";

    if (shouldRedirect) {
      return <Redirect to={{ pathname: "/" }} />;
    }

    return (
      <div className="bwm-form">
        <div className="row">
          <div className="col-md-5">
            <h1 className="page-title">Login</h1>
            {message && <div className="alert alert-success">{message}</div>}
            <LoginForm onSubmit={this.signIn} />
            <ApiErrors errors={errors} />
          </div>
          <div className="col-md-6 ml-auto">
            <div className="image-container">
              <h2 className="catchphrase">
                Hundreds of awesome places in reach of few clicks.
              </h2>
              <img src="/images/login-image.jpg" alt="Login an user" />
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default withAuth(Login);
