// GIT-USERS/Jerga/bwm-react/src/components/rental/rental-detail/RentalUpdate.js
import React from "react";
import { connect } from "react-redux";
import RentalMap from "./RentalMap";
import Booking from "components/booking/Booking";

import { UserGuard } from "../../shared/auth/UserGuard";
import { RentalAssets } from "./RentalAssets";
import { toUpperCase } from "helpers";

import { EditableInput } from "../../shared/editable/EditableInput";
import { EditableText } from "../../shared/editable/EditableText";
import { EditableSelect } from "../../shared/editable/EditableSelect";
import { EditableImage } from "../../shared/editable/EditableImage";

import * as actions from "actions";

class RentalUpdate extends React.Component {
  constructor() {
    super();

    this.state = {
      isAllowed: false,
      isFetching: true,
    };

    this.updateRental = this.updateRental.bind(this);
    this.resetRentalErrors = this.resetRentalErrors.bind(this);
    this.verifyRentalOwner = this.verifyRentalOwner.bind(this);
  }

  componentWillMount() {
    // Dispatch action
    const rentalId = this.props.match.params.id;

    this.props.dispatch(actions.fetchRentalById(rentalId));
  }

  componentDidMount() {
    this.verifyRentalOwner();
  }

  updateRental(rentalData) {
    const {
      rental: { _id },
      dispatch,
    } = this.props;

    dispatch(actions.updateRental(_id, rentalData));
  }

  resetRentalErrors() {
    this.props.dispatch(actions.resetRentalErrors());
  }

  verifyRentalOwner() {
    const rentalId = this.props.match.params.id;
    this.setState({ isFetching: true });

    return actions.verifyRentalOwner(rentalId).then(
      () => {
        this.setState({ isAllowed: true, isFetching: false });
      },
      () => {
        this.setState({ isAllowed: false, isFetching: false });
      }
    );
  }

  render() {
    const { rental, errors } = this.props;
    const { isFetching, isAllowed } = this.state;

    if (rental._id) {
      return (
        <UserGuard isAllowed={isAllowed} isFetching={isFetching}>
          <section id="rentalDetails">
            <div className="upper-section">
              <div className="row">
                <div className="col-md-6">
                  <EditableImage
                    entity={rental}
                    entityField={"image"}
                    errors={errors}
                    updateEntity={this.updateRental}
                  >
                    {" "}
                  </EditableImage>
                </div>
                <div className="col-md-6">
                  <RentalMap location={`${rental.city}, ${rental.street}`} />
                </div>
              </div>
            </div>

            <div className="details-section">
              <div className="row">
                <div className="col-md-8">
                  <div className="rental">
                    <label
                      className={`rental-label rental-type ${rental.category}`}
                    >
                      {" "}
                      Shared{" "}
                    </label>
                    <EditableSelect
                      entity={rental}
                      entityField={"shared"}
                      className={`rental-type ${rental.category}`}
                      updateEntity={this.updateRental}
                      options={[true, false]}
                      containerStyle={{ display: "inline-block" }}
                      errors={errors}
                      resetErrors={this.resetRentalErrors}
                    />

                    <EditableSelect
                      entity={rental}
                      entityField={"category"}
                      className={`rental-type ${rental.category}`}
                      updateEntity={this.updateRental}
                      options={["apartment", "house", "condo"]}
                      errors={errors}
                      resetErrors={this.resetRentalErrors}
                    />

                    <div className="rental-owner">
                      <img
                        src="https://api.adorable.io/avatars/285/abott@adorable.png"
                        alt="owner"
                      />
                      <span>{rental.user && rental.user.username}</span>
                    </div>

                    <EditableInput
                      entity={rental}
                      entityField={"title"}
                      className={"rental-title"}
                      updateEntity={this.updateRental}
                      errors={errors}
                      resetErrors={this.resetRentalErrors}
                    />

                    <EditableInput
                      entity={rental}
                      entityField={"city"}
                      className={"rental-city"}
                      updateEntity={this.updateRental}
                      errors={errors}
                      formatPipe={[toUpperCase]}
                      resetErrors={this.resetRentalErrors}
                    />

                    <EditableInput
                      entity={rental}
                      entityField={"street"}
                      className={"rental-street"}
                      updateEntity={this.updateRental}
                      errors={errors}
                      resetErrors={this.resetRentalErrors}
                    />

                    <div className="rental-room-info">
                      <span>
                        <i className="fa fa-building"></i>
                        <EditableInput
                          entity={rental}
                          entityField={"bedrooms"}
                          className={"rental-bedrooms"}
                          containerStyle={{ display: "inline-block" }}
                          updateEntity={this.updateRental}
                          errors={errors}
                          resetErrors={this.resetRentalErrors}
                        />{" "}
                        bedrooms
                      </span>
                      <span>
                        <i className="fa fa-user"></i> {rental.bedrooms + 4}{" "}
                        guests
                      </span>
                      <span>
                        <i className="fa fa-bed"></i> {rental.bedrooms + 2} beds
                      </span>
                    </div>
                    <EditableText
                      entity={rental}
                      entityField={"description"}
                      className={"rental-description"}
                      updateEntity={this.updateRental}
                      rows={6}
                      cols={50}
                      errors={errors}
                      resetErrors={this.resetRentalErrors}
                    />
                    <hr></hr>
                    <RentalAssets />
                  </div>
                </div>
                <div className="col-md-4">
                  <Booking rental={rental} />
                </div>
              </div>
            </div>
          </section>
        </UserGuard>
      );
    } else {
      return <h1> Loading... </h1>;
    }
  }
}

function mapStateToProps(state) {
  return {
    rental: state.rental.data,
    errors: state.rental.errors,
  };
}

export default connect(mapStateToProps)(RentalUpdate);

// GIT-USERS/Jerga/initialNgProject/src/app/rental/rental-update/rental-update.component.ts
import { Component, OnInit } from "@angular/core";
import { ActivatedRoute } from "@angular/router";
import { RentalService } from "../shared/rental.service";
import { Rental } from "../shared/rental.model";
import { ToastrService } from "ngx-toastr";
import { HttpErrorResponse } from "@angular/common/http";
import { UcWordsPipe } from "ngx-pipes";

import { Subject } from "rxjs";

@Component({
  selector: "bwm-rental-update",
  templateUrl: "./rental-update.component.html",
  styleUrls: ["./rental-update.component.scss"],
})
export class RentalUpdateComponent implements OnInit {
  rental: Rental;

  rentalCategories: string[] = Rental.CATEGORIES;

  locationSubject: Subject<any> = new Subject();

  constructor(
    private route: ActivatedRoute,
    private rentalService: RentalService,
    private toastr: ToastrService,
    private upperPipe: UcWordsPipe
  ) {
    this.transformLocation = this.transformLocation.bind(this);
  }

  ngOnInit() {
    this.route.params.subscribe((params) => {
      this.getRental(params["rentalId"]);
    });
  }

  transformLocation(location: string): string {
    return this.upperPipe.transform(location);
  }

  getRental(rentalId: string) {
    this.rentalService.getRentalById(rentalId).subscribe((rental: Rental) => {
      this.rental = rental;
    });
  }

  updateRental(rentalId: string, rentalData: any) {
    this.rentalService.updateDental(rentalId, rentalData).subscribe(
      (updatedRental: Rental) => {
        this.rental = updatedRental;

        if (rentalData.city || rentalData.street) {
          this.locationSubject.next(
            this.rental.city + ", " + this.rental.street
          );
        }
      },
      (errorResponse: HttpErrorResponse) => {
        this.toastr.error(errorResponse.error.errors[0].detail, "Error");
        this.getRental(rentalId);
      }
    );
  }

  countBedroomAssets(assetsNum: number) {
    return parseInt(<any>this.rental.bedrooms || 0, 10) + assetsNum;
  }
}

<section id="rentalDetails" *ngIf="rental">
  <div class="upper-section">
    <div class="row">
      <div class="col-md-6">
        <bwm-editable-image
          [(entity)]="rental"
          [field]="'image'"
          (entityUpdated)="updateRental(rental._id, $event)"
        >
        </bwm-editable-image>
      </div>
      <div class="col-md-6">
        <bwm-map
          [locationSubject]="locationSubject"
          [location]="rental.city + ', ' + rental.street"
        >
        </bwm-map>
      </div>
    </div>
  </div>

  <div class="details-section">
    <div class="row">
      <div class="col-md-8">
        <div class="rental">
          <h2 class="rental-type {{ rental.category }}">
            Shared
            <bwm-editable-select
              [(entity)]="rental"
              [field]="'shared'"
              [options]="[true, false]"
              [style]="{ display: 'inline-block' }"
              [className]="'rental-shared'"
              (entityUpdated)="updateRental(rental._id, $event)"
            >
            </bwm-editable-select>

            <bwm-editable-select
              [(entity)]="rental"
              [field]="'category'"
              [options]="rentalCategories"
              [className]="'rental-category'"
              (entityUpdated)="updateRental(rental._id, $event)"
            >
            </bwm-editable-select>
          </h2>
          <div class="rental-owner">
            <img
              src="https://api.adorable.io/avatars/285/abott@adorable.png"
              alt=""
            />
            <span>{{ rental.user.username }}</span>
          </div>

          <bwm-editable-input
            [(entity)]="rental"
            [field]="'title'"
            [className]="'rental-title'"
            (entityUpdated)="updateRental(rental._id, $event)"
          >
          </bwm-editable-input>

          <bwm-editable-input
            [(entity)]="rental"
            [field]="'city'"
            [transformView]="transformLocation"
            [className]="'rental-city'"
            (entityUpdated)="updateRental(rental._id, $event)"
          >
          </bwm-editable-input>

          <bwm-editable-input
            [(entity)]="rental"
            [field]="'street'"
            [transformView]="transformLocation"
            [className]="'rental-street'"
            (entityUpdated)="updateRental(rental._id, $event)"
          >
          </bwm-editable-input>

          <div class="rental-room-info">
            <span
              ><i class="fa fa-building"></i>
              <bwm-editable-input
                [(entity)]="rental"
                [field]="'bedrooms'"
                [type]="'number'"
                [style]="{ display: 'inline-block' }"
                [className]="'rental-bedrooms'"
                (entityUpdated)="updateRental(rental._id, $event)"
              >
              </bwm-editable-input>
              bedrooms
            </span>
            <span
              ><i class="fa fa-user"></i>
              {{ countBedroomAssets(4) }} guests</span
            >
            <span
              ><i class="fa fa-bed"></i> {{ countBedroomAssets(2) }} beds</span
            >
          </div>
          <bwm-editable-textarea
            [(entity)]="rental"
            [field]="'description'"
            [className]="'rental-description'"
            [rows]="'6'"
            [cols]="'50'"
            (entityUpdated)="updateRental(rental._id, $event)"
          >
          </bwm-editable-textarea>

          <hr />
          <div class="rental-assets">
            <h3 class="title">Assets</h3>
            <div class="row">
              <div class="col-md-6">
                <span><i class="fa fa-asterisk"></i> Cooling</span>
                <span><i class="fa fa-thermometer"></i> Heating</span>
                <span><i class="fa fa-location-arrow"></i> Iron</span>
              </div>
              <div class="col-md-6">
                <span><i class="fa fa-desktop"></i> Working area</span>
                <span><i class="fa fa-cube"></i> Washing machine</span>
                <span><i class="fa fa-cube"></i> Dishwasher</span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <bwm-rental-detail-booking [rental]="rental">
        </bwm-rental-detail-booking>
      </div>
    </div>
  </div>
</section>
