// GIT-USERS/Jerga/vue-3-updates/src/components/ResourceDetail.vue
<template>
  <div v-if="resource?._id" :class="`card ${theme()}`">
    <div class="card-header">
      {{ resource.title }}
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>{{ resource.description }}</p>
        <footer class="text-muted mb-2">{{ resource.type }}</footer>
        <a
          target="_blank"
          :href="resource.link"
          class="btn btn-outline-primary"
        >
          Resource Link
        </a>
      </blockquote>
    </div>
  </div>
  <div v-else class="card">
    <div class="card-body">No Resource Selected</div>
  </div>
</template>
<script>
export default {
  props: {
    resource: {
      validator: (prop) => typeof prop === "object" || prop === null,
      required: true,
    },
  },
  inject: ["theme"],
};
</script>

<style scoped>
.card.dark {
  color: black;
}
</style>

// GIT-USERS/Jerga/angular-basics/src/app/resource/components/resource-detail/resource-detail.component.ts
import { Component, Input } from '@angular/core';
import { Resource } from '../../shared/resource.model';
import { SettingsService } from '../../shared/settings.service';

@Component({
  selector: 'app-resource-detail-card',
  templateUrl: './resource-detail.component.html',
  styleUrls: ['./resource-detail.component.scss'],
})
export class ResourceDetailCardComponent {
  @Input() resource: Resource;
  @Input() isButtonDisplayed = true;

  constructor(private settingsService: SettingsService) {}

  get theme(): string {
    return this.settingsService.settings?.theme;
  }
}

<div *ngIf="!resource?._id; else detailView" class="card">
  <div class="card-body">No resource selected :(</div>
</div>

<ng-template #detailView>
  <div class="card" [ngClass]="theme">
    <div class="card-header">
      {{ resource?.title || "Default Title" }}
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>{{ resource?.description }}</p>
        <footer class="text-muted mb-2">{{ resource?.type }}</footer>
      </blockquote>
      <div class="mb-2">
        <a [href]="resource?.link" target="_blank">{{ resource.link }}</a>
      </div>
      <a
        *ngIf="isButtonDisplayed"
        routerLink="/resources/{{ resource?._id }}"
        class="btn btn-outline-primary"
        >Detail</a
      >
    </div>
  </div>
</ng-template>
