// GIT-USERS/Jerga/react-basics/src/components/ResourceForm.js
import React, { useState, useEffect } from "react";
const RESOURCE_TYPES = ["blog", "video", "book"];
const BASE_RESOURCE = {
  title: "",
  description: "",
  type: "",
  link: "",
};

const ResourceForm = ({ resource, onSubmit, alert }) => {
  const [uResource, setUResource] = useState(resource || BASE_RESOURCE);

  useEffect(() => {
    resource?._id ? setUResource(resource) : setUResource(BASE_RESOURCE);
  }, [resource]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setUResource({ ...uResource, [name]: value });
  };

  const handleSubmit = () => {
    onSubmit(uResource);
  };

  return (
    <>
      {alert?.success && (
        <div className="alert alert-success">{alert.success}</div>
      )}
      {alert?.error && <div className="alert alert-danger">{alert.error}</div>}
      <form className="resource-form">
        <div className="mb-3">
          <label htmlFor="title">Title</label>
          <input
            onChange={handleChange}
            value={uResource.title}
            name="title"
            type="text"
            className="form-control"
            id="title"
            placeholder="How to survive in mountains"
          />
        </div>
        <div className="mb-3">
          <label htmlFor="description">Description</label>
          <textarea
            onChange={handleChange}
            value={uResource.description}
            name="description"
            className="form-control"
            id="description"
            placeholder="Just some description"
          ></textarea>
        </div>
        <div className="mb-3">
          <label htmlFor="link">Resource Link</label>
          <div className="input-group">
            <input
              onChange={handleChange}
              value={uResource.link}
              name="link"
              type="text"
              className="form-control"
              id="link"
              placeholder="Username"
            />
          </div>
        </div>
        <div className="mb-3">
          <label htmlFor="type">Type</label>
          <select
            onChange={handleChange}
            className="form-control"
            name="type"
            value={uResource.type}
            id="type"
          >
            {RESOURCE_TYPES.map((type) => (
              <option key={type} value={type}>
                {type}
              </option>
            ))}
          </select>
        </div>
        <hr className="mb-4" />
        <button
          onClick={handleSubmit}
          className="btn btn-primary btn-lg btn-block"
          type="button"
        >
          Submit
        </button>
      </form>
    </>
  );
};

export default ResourceForm;

// GIT-USERS/Jerga/vue-basics/src/components/ResourceForm.vue
<template>
  <form @submit.prevent="submitForm">
    <div v-if="alert?.success" class="alert alert-success">
      {{ alert.success }}
    </div>
    <div v-if="alert?.error" class="alert alert-danger">
      {{ alert.error }}
    </div>
    <div class="mb-3">
      <label htmlFor="firstName">Title</label>
      <input
        v-model="uResource.title"
        type="text"
        class="form-control"
        id="title"
        placeholder="How to survice in mountains"
      />
    </div>
    <div class="mb-3">
      <label for="description">Description</label>
      <textarea
        v-model="uResource.description"
        class="form-control"
        id="description"
        placeholder="Just some description"
      ></textarea>
    </div>
    <div class="mb-3">
      <label htmlFor="link">Resource Link</label>
      <div class="input-group">
        <input
          v-model="uResource.link"
          type="text"
          class="form-control"
          id="link"
          placeholder="Username"
        />
      </div>
    </div>
    <div class="mb-3">
      <label htmlFor="link">Type</label>
      <select class="form-control" id="link" v-model="uResource.type">
        <option
          v-for="resourceType in types"
          :key="resourceType"
          :value="resourceType"
        >
          {{ resourceType }}
        </option>
      </select>
    </div>
    <hr class="mb-4" />
    <button class="btn btn-primary btn-lg btn-block" type="submit">
      Submit
    </button>
  </form>
</template>

<script>
export default {
  props: {
    resource: Object,
    alert: Object,
  },
  data() {
    return {
      uResource: { ...this.resource },
      types: ["blog", "video", "book"],
    };
  },
  emits: ["on-form-submit"],
  watch: {
    resource(newResource) {
      this.uResource = { ...newResource };
    },
  },
  methods: {
    submitForm() {
      this.$emit("on-form-submit", this.uResource);
    },
  },
};
</script>
