// GIT-USERS/Jerga/react-basics/src/components/ResourceSearch.js
import React from "react";
import { DebounceInput } from "react-debounce-input";

const ResourceSearch = ({ onSearch }) => {
  return (
    <form className="card p-2">
      <div className="input-group">
        <DebounceInput
          onChange={(e) => onSearch(e.target.value)}
          debounceTimeout={400}
          className="form-control"
          placeholder="Some title"
        />
      </div>
    </form>
  );
};

export default ResourceSearch;

// GIT-USERS/Jerga/vue-basics/src/components/ResourceSearch.vue
<template>
  <form class="card p-2">
    <div class="input-group">
      <input
        @keyup="$emit('on-search', $event.target.value)"
        type="text"
        class="form-control"
        placeholder="Some title"
      />
    </div>
  </form>
</template>

<script>
export default {
  emits: ["on-search"],
};
</script>
