// GIT-USERS/Jerga/vue-basics/src/components/Header.vue
<template>
  <div class="py-5 text-center">
    <teleport to="#teleportContent">
      <div class="user-container">
        <suspense>
          <template #default>
            <user-panel />
          </template>
          <template #fallback> Loading...... </template>
        </suspense>
      </div>
    </teleport>
    <img height="150" src="../assets/logo.png" />
    <h2>Keep Resources</h2>
    <p class="lead">Keep your resource at once place</p>
    <router-link
      :to="{ name: 'resourceHomePage' }"
      class="btn btn-outline-primary mr-2"
      >Home</router-link
    >
    <router-link
      :to="{ name: 'resourceNewPage' }"
      class="btn btn-outline-primary"
      >New</router-link
    >
  </div>
</template>

<script>
import UserPanel from "@/components/UserPanel";
export default {
  components: { UserPanel },
};
</script>

<style scoped>
.user-container {
  padding: 20px;
  font-weight: bold;
  font-size: 20px;
  background-color: #ffd16c;
}
</style>

// GIT-USERS/Jerga/react-basics/src/components/Header.js
import React from "react";
import { NavLink } from "react-router-dom";

const Header = () => (
  <div className="py-5 text-center app-header">
    <img
      alt="React logo"
      style={{ height: "150px" }}
      src={process.env.PUBLIC_URL + "/logo512.png"}
    />
    <h2>Keep Resources</h2>
    <p className="lead">Keep your resource at once place</p>
    <NavLink to="/" exact className="btn btn-outline-primary mr-2">
      Home
    </NavLink>
    <NavLink to="/resources/new" className="btn btn-outline-primary mr-2">
      New
    </NavLink>
    <NavLink to="/about" className="btn btn-outline-primary">
      About
    </NavLink>
  </div>
);

export default Header;
