// GIT-USERS/Jerga/vue-3-updates/src/components/ResourceDetail.vue
<template>
  <div v-if="resource?._id" :class="`card ${theme()}`">
    <div class="card-header">
      {{ resource.title }}
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>{{ resource.description }}</p>
        <footer class="text-muted mb-2">{{ resource.type }}</footer>
        <a
          target="_blank"
          :href="resource.link"
          class="btn btn-outline-primary"
        >
          Resource Link
        </a>
      </blockquote>
    </div>
  </div>
  <div v-else class="card">
    <div class="card-body">No Resource Selected</div>
  </div>
</template>
<script>
export default {
  props: {
    resource: {
      validator: (prop) => typeof prop === "object" || prop === null,
      required: true,
    },
  },
  inject: ["theme"],
};
</script>

<style scoped>
.card.dark {
  color: black;
}
</style>

// GIT-USERS/Jerga/react-basics/src/components/ResourceDetail.js
import React from "react";
import { Link } from "react-router-dom";
import { useSettings } from "../context/SettingsProvider";

const ResourceDetail = ({ resource }) => {
  const { settings } = useSettings();

  if (!resource?._id) {
    return (
      <div className="card">
        <div className="card-body">No resource selected :(</div>
      </div>
    );
  }

  return (
    <div className={`card ${settings?.theme}`}>
      <div className="card-header">{resource.title}</div>
      <div className="card-body">
        <blockquote className="blockquote mb-0">
          <p>{resource.description}</p>
          <footer className="text-muted mb-2">{resource.type}</footer>
        </blockquote>
        <Link to={`/resources/${resource._id}`} className="btn btn-primary">
          See the resource
        </Link>
      </div>
    </div>
  );
};

export default ResourceDetail;
