// GIT-USERS/Jerga/angular-basics/src/app/resource/components/resource-list/resource-list.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Resource } from '../../shared/resource.model';
import { SettingsService } from '../../shared/settings.service';

@Component({
  selector: 'app-resource-list',
  templateUrl: './resource-list.component.html',
  styleUrls: ['./resource-list.component.scss'],
})
export class ResourceListComponent {
  @Input() resources: Resource[];
  @Input() activeId: string;
  @Output() onResourceClick = new EventEmitter<Resource>();

  constructor(private settingsService: SettingsService) {}

  get theme(): string {
    return this.settingsService.settings?.theme;
  }

  get jsonResources() {
    return JSON.stringify(this.resources);
  }

  handleResourceSelect(resource: Resource) {
    this.onResourceClick.next(resource);
  }
}

<ul class="resource-list list-group mb-3" [ngClass]="theme">
  <li
    *ngFor="let resource of resources"
    (click)="handleResourceSelect(resource)"
    [ngClass]="{ 'is-active': activeId === resource._id }"
    class="
      list-group-item
      resource-list-item
      d-flex
      justify-content-between
      lh-condensed
    "
  >
    <div>
      <h6 class="my-0">{{ resource.title }}</h6>
      <small class="text-muted">{{ resource.description }}</small>
    </div>
    <span class="text-muted">{{ resource.type }}</span>
  </li>
</ul>

// GIT-USERS/Jerga/react-basics/src/components/ResourceList.js
import React from "react";
import { useSettings } from "../context/SettingsProvider";

const ResourceList = ({ resources, onItemClick, activeId }) => {
  const { settings } = useSettings();
  return (
    <ul className={`list-group mb-3 resource-list ${settings?.theme}`}>
      {resources.map((resource) => (
        <li
          onClick={() => onItemClick(resource)}
          key={resource._id}
          className={`${
            activeId === resource._id ? "is-active" : ""
          } resource-list-item list-group-item d-flex justify-content-between lh-condensed`}
        >
          <div>
            <h6 className="my-0">{resource.title}</h6>
            <small className="text-muted">{resource.description}</small>
          </div>
          <span className="text-muted">{resource.type}</span>
        </li>
      ))}
    </ul>
  );
};

export default ResourceList;
