// GIT-USERS/Jerga/vue-basics/src/components/ResourceUpdate.vue
<template>
  <div v-if="!resource?._id" class="card">
    <div class="card-body">No Resource is selected :(</div>
  </div>
  <resource-form
    v-else
    :alert="alert"
    :resource="resource"
    @on-form-submit="updateResource"
  />
</template>

<script>
import ResourceForm from "@/components/ResourceForm";
import { updateResourceApi } from "@/actions";
import alertMixin from "@/mixins/alert";
export default {
  components: { ResourceForm },
  props: {
    resource: Object,
  },
  mixins: [alertMixin],
  emits: ["on-resource-update"],
  beforeUnmount() {
    this.clearAlertTimeout();
  },
  watch: {
    resource(newResource, previousResource) {
      if (newResource?._id !== previousResource?._id) {
        this.clearAlertTimeout();
        this.alert = this.initAlert();
      }
    },
  },
  methods: {
    async updateResource(resource) {
      try {
        const updatedResource = await updateResourceApi(resource._id, resource);
        this.$emit("on-resource-update", updatedResource);
        this.setAlert("success", "Resource was updated!");
      } catch (errorMessage) {
        this.setAlert("error", errorMessage);
      }
    },
  },
};
</script>

// GIT-USERS/Jerga/react-basics/src/components/ResourceUpdate.js
import React from "react";
import ResourceForm from "./ResourceForm";
import withAlert from "../hoc/withAlert";
import { updateResourceApi } from "../actions";

const ResourceUpdate = ({
  resource,
  onResourceUpdate,
  displayAlert,
  alert,
}) => {
  const updateResource = async (resourceData) => {
    try {
      const updatedResource = await updateResourceApi(
        resourceData._id,
        resourceData
      );
      onResourceUpdate(updatedResource);
      displayAlert("success", "Resouce was updated!");
    } catch (e) {
      displayAlert("error", e);
    }
  };

  if (!resource?._id) {
    return "Resource update is not available!";
  }

  return (
    <ResourceForm alert={alert} onSubmit={updateResource} resource={resource} />
  );
};

export default withAlert(ResourceUpdate);
