// GIT-USERS/Jerga/vue-3-updates/src/components/ResourceForm.vue
<template>
  <form>
    <div class="mb-3">
      <label htmlFor="title">Title</label>
      <input
        :value="title"
        @input="changeTitle($event.target.value)"
        type="text"
        class="form-control"
        id="title"
        placeholder="How to survice in mountains"
      />
    </div>
    <div class="mb-3">
      <label for="description">Description</label>
      <textarea
        :value="description"
        @input="changeDescription($event.target.value)"
        class="form-control"
        id="description"
        placeholder="Just some description"
      >
      </textarea>
    </div>
    <div class="mb-3">
      <label htmlFor="link"
        >Link <span class="text-muted">(Optional)</span></label
      >
      <input
        :value="link"
        @input="changeLink($event.target.value)"
        type="text"
        class="form-control"
        id="link"
        placeholder="Link to resource"
      />
    </div>
    <div class="mb-3">
      <select
        class="form-control"
        name="type"
        :value="type"
        @change="changeType($event.target.value)"
        id="resourceType"
      >
        <option v-for="type in types" :key="type" :value="type">
          {{ type }}
        </option>
      </select>
    </div>
    <hr class="mb-4" />
    <button
      @click="submitForm"
      class="btn btn-primary btn-lg btn-block"
      type="button"
    >
      Submit
    </button>
  </form>
</template>
<script>
export default {
  props: {
    title: String,
    description: String,
    link: String,
    type: String,
  },
  data() {
    return {
      types: ["blog", "book", "video"],
    };
  },
  methods: {
    submitForm() {
      this.$emit("on-form-submit");
    },
    changeTitle(title) {
      this.$emit("update:title", title);
    },
    changeDescription(description) {
      this.$emit("update:description", description);
    },
    changeLink(link) {
      this.$emit("update:link", link);
    },
    changeType(type) {
      this.$emit("update:type", type);
    },
  },
};
</script>

// GIT-USERS/Jerga/react-basics/src/components/ResourceForm.js
import React, { useState, useEffect } from "react";
const RESOURCE_TYPES = ["blog", "video", "book"];
const BASE_RESOURCE = {
  title: "",
  description: "",
  type: "",
  link: "",
};

const ResourceForm = ({ resource, onSubmit, alert }) => {
  const [uResource, setUResource] = useState(resource || BASE_RESOURCE);

  useEffect(() => {
    resource?._id ? setUResource(resource) : setUResource(BASE_RESOURCE);
  }, [resource]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setUResource({ ...uResource, [name]: value });
  };

  const handleSubmit = () => {
    onSubmit(uResource);
  };

  return (
    <>
      {alert?.success && (
        <div className="alert alert-success">{alert.success}</div>
      )}
      {alert?.error && <div className="alert alert-danger">{alert.error}</div>}
      <form className="resource-form">
        <div className="mb-3">
          <label htmlFor="title">Title</label>
          <input
            onChange={handleChange}
            value={uResource.title}
            name="title"
            type="text"
            className="form-control"
            id="title"
            placeholder="How to survive in mountains"
          />
        </div>
        <div className="mb-3">
          <label htmlFor="description">Description</label>
          <textarea
            onChange={handleChange}
            value={uResource.description}
            name="description"
            className="form-control"
            id="description"
            placeholder="Just some description"
          ></textarea>
        </div>
        <div className="mb-3">
          <label htmlFor="link">Resource Link</label>
          <div className="input-group">
            <input
              onChange={handleChange}
              value={uResource.link}
              name="link"
              type="text"
              className="form-control"
              id="link"
              placeholder="Username"
            />
          </div>
        </div>
        <div className="mb-3">
          <label htmlFor="type">Type</label>
          <select
            onChange={handleChange}
            className="form-control"
            name="type"
            value={uResource.type}
            id="type"
          >
            {RESOURCE_TYPES.map((type) => (
              <option key={type} value={type}>
                {type}
              </option>
            ))}
          </select>
        </div>
        <hr className="mb-4" />
        <button
          onClick={handleSubmit}
          className="btn btn-primary btn-lg btn-block"
          type="button"
        >
          Submit
        </button>
      </form>
    </>
  );
};

export default ResourceForm;
