// GIT-USERS/Jerga/bwm-react-new/src/pages/RentalDetail.js
import React from "react";
import { withRouter } from "react-router-dom";
import { connect } from "react-redux";
import { fetchRentalById } from "actions";
import RentalInfo from "components/rental/RentalInfo";
import TomMap from "components/map/TomMap";
import BookingReserve from "components/booking/BookingReserve";

class RentalDetail extends React.Component {
  componentDidMount() {
    const { id } = this.props.match.params;
    this.props.dispatch(fetchRentalById(id));
  }

  componentWillUnmount() {
    this.props.dispatch({ type: "UNMOUNT_RENTAL" });
  }

  get location() {
    const {
      rental: { street, city },
    } = this.props;
    return street && city && city + ", " + street;
  }

  render() {
    const { rental, isFetching, isAuth } = this.props;
    if (isFetching || !rental._id) {
      return null;
    }
    return (
      <section id="rentalDetails">
        <div className="upper-section">
          <div className="row">
            <div className="col-md-6">
              <img
                className="rental-img"
                src={rental.image.url}
                alt={rental.title}
              />
            </div>
            <div className="col-md-6">
              <TomMap location={this.location} />
            </div>
          </div>
        </div>
        <div className="details-section">
          <div className="row">
            <div className="col-md-8">
              <RentalInfo rental={rental} />
            </div>
            <div className="col-md-4">
              <BookingReserve rental={rental} isAuth={isAuth} />
            </div>
          </div>
        </div>
      </section>
    );
  }
}

const mapStateToProps = ({ rental, auth: { isAuth } }) => ({
  rental: rental.item,
  isFetching: rental.isFetching,
  isAuth: isAuth,
});

const RentalDetailWithRouter = withRouter(RentalDetail);
export default connect(mapStateToProps)(RentalDetailWithRouter);

// GIT-USERS/Jerga/book-with-me-ng/src/app/rental/rental-detail/rental-detail.component.ts
import { Component, OnInit } from "@angular/core";
import { ActivatedRoute } from "@angular/router";
import { RentalService } from "../shared/rental.service";
import { HelperService } from "../../shared/service/helper.service";

import { Rental } from "../shared/rental.model";

@Component({
  selector: "bwm-rental-detail",
  templateUrl: "./rental-detail.component.html",
  styleUrls: ["rental-detail.component.scss"],
})
export class RentalDetailComponent implements OnInit {
  public rental: Rental;

  constructor(
    public rentalService: RentalService,
    public route: ActivatedRoute,
    public helper: HelperService
  ) {}

  ngOnInit() {
    this.route.params.subscribe((params) => {
      this.getRentalById(params["rentalId"]);
    });
  }

  getRentalById(id: string) {
    this.rentalService.getRentalById(id).subscribe((rental) => {
      this.rental = rental;
    });
  }
}

<section id="rentalDetails" *ngIf="rental">
  <div class="upper-section">
    <div class="row">
      <div class="col-md-6">
        <img src="{{ rental.image }}" alt="" />
      </div>
      <div class="col-md-6">
        <bwm-map [location]="rental.city + ', ' + rental.street"></bwm-map>
      </div>
    </div>
  </div>

  <div class="details-section">
    <div class="row">
      <div class="col-md-8">
        <bwm-rental-detail-info [rental]="rental"> </bwm-rental-detail-info>
      </div>
      <div class="col-md-4">
        <bwm-rental-detail-booking
          [rental]="rental"
        ></bwm-rental-detail-booking>
      </div>
    </div>
  </div>
</section>
