// GIT-USERS/Jerga/bwm-react/src/components/rental/rental-detail/RentalDetail.js
import React from "react";
import { connect } from "react-redux";
import { RentalDetailInfo } from "./RentalDetailInfo";
import RentalMap from "./RentalMap";
import Booking from "components/booking/Booking";

import * as actions from "actions";

class RentalDetail extends React.Component {
  componentWillMount() {
    // Dispatch action
    const rentalId = this.props.match.params.id;

    this.props.dispatch(actions.fetchRentalById(rentalId));
  }
  render() {
    const { rental } = this.props;

    if (rental._id) {
      return (
        <section id="rentalDetails">
          <div className="upper-section">
            <div className="row">
              <div className="col-md-6">
                <img src={rental.image} alt=""></img>
              </div>
              <div className="col-md-6">
                <RentalMap location={`${rental.city}, ${rental.street}`} />
              </div>
            </div>
          </div>

          <div className="details-section">
            <div className="row">
              <div className="col-md-8">
                <RentalDetailInfo rental={rental} />
              </div>
              <div className="col-md-4">
                <Booking rental={rental} />
              </div>
            </div>
          </div>
        </section>
      );
    } else {
      return <h1> Loading... </h1>;
    }
  }
}

function mapStateToProps(state) {
  return {
    rental: state.rental.data,
    errors: state.rental.errors,
  };
}

export default connect(mapStateToProps)(RentalDetail);

// GIT-USERS/Jerga/book-with-me-ng/src/app/rental/rental-detail/rental-detail.component.ts
import { Component, OnInit } from "@angular/core";
import { ActivatedRoute } from "@angular/router";
import { RentalService } from "../shared/rental.service";
import { HelperService } from "../../shared/service/helper.service";

import { Rental } from "../shared/rental.model";

@Component({
  selector: "bwm-rental-detail",
  templateUrl: "./rental-detail.component.html",
  styleUrls: ["rental-detail.component.scss"],
})
export class RentalDetailComponent implements OnInit {
  public rental: Rental;

  constructor(
    public rentalService: RentalService,
    public route: ActivatedRoute,
    public helper: HelperService
  ) {}

  ngOnInit() {
    this.route.params.subscribe((params) => {
      this.getRentalById(params["rentalId"]);
    });
  }

  getRentalById(id: string) {
    this.rentalService.getRentalById(id).subscribe((rental) => {
      this.rental = rental;
    });
  }
}

<section id="rentalDetails" *ngIf="rental">
  <div class="upper-section">
    <div class="row">
      <div class="col-md-6">
        <img src="{{ rental.image }}" alt="" />
      </div>
      <div class="col-md-6">
        <bwm-map [location]="rental.city + ', ' + rental.street"></bwm-map>
      </div>
    </div>
  </div>

  <div class="details-section">
    <div class="row">
      <div class="col-md-8">
        <bwm-rental-detail-info [rental]="rental"> </bwm-rental-detail-info>
      </div>
      <div class="col-md-4">
        <bwm-rental-detail-booking
          [rental]="rental"
        ></bwm-rental-detail-booking>
      </div>
    </div>
  </div>
</section>
