// GIT-USERS/Jerga/book-with-me-ng/src/app/shared/component/header/header.component.ts
import { Component } from "@angular/core";
import { UserService } from "../../../user/shared/user.service";
import { Router } from "@angular/router";

@Component({
  selector: "bwm-header",
  templateUrl: "./header.component.html",
  styleUrls: ["./header.component.scss"],
})
export class HeaderComponent {
  constructor(public auth: UserService, public router: Router) {}

  public logout(): void {
    this.auth.logout().subscribe(() => {
      this.router.navigate(["login"]);
    });
  }

  public search(city: string): void {
    city
      ? this.router.navigate([`rentals/${city}/homes`])
      : this.router.navigate(["rentals"]);
  }
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" routerLink="/rentals"
    >BookWithMe<img src="favicon.ico" alt=""
  /></a>
  <form class="form-inline my-2 my-lg-0">
    <input
      #citySearch
      (keyup.enter)="search(citySearch.value)"
      class="form-control mr-sm-2 bwm-search"
      type="search"
      placeholder="Try 'New York'"
      aria-label="Search"
    />
    <button
      class="btn btn-outline-success my-2 my-sm-0 btn-bwm-search"
      (click)="search(citySearch.value)"
      type="button"
    >
      Search
    </button>
  </form>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNavAltMarkup"
    aria-controls="navbarNavAltMarkup"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">
      <div *ngIf="auth.isAuthenticated()" class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle"
          href="http://example.com"
          id="navbarDropdownMenuLink"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          Owner Section
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" routerLink="/rentals/new">Create Rental</a>
          <a class="dropdown-item" routerLink="/manage/rentals"
            >Manage Rentals</a
          >
          <a class="dropdown-item" routerLink="/manage/bookings"
            >Manage Bookings</a
          >
        </div>
      </div>
      <ng-container *ngIf="auth.isAuthenticated()">
        <a class="nav-item nav-link"> Welcome {{ auth.getUsername() }}</a>
        <a class="nav-item nav-link clickable" (click)="logout()">Logout</a>
      </ng-container>
      <ng-container *ngIf="!auth.isAuthenticated()">
        <a class="nav-item nav-link active clickable" routerLink="login"
          >Login <span class="sr-only">(current)</span></a
        >
        <a class="nav-item nav-link clickable" routerLink="register"
          >Register</a
        >
      </ng-container>
    </div>
  </div>
</nav>

// GIT-USERS/Jerga/bwm-react/src/components/shared/Header.js
import React from "react";
import { Link, withRouter } from "react-router-dom";
import { connect } from "react-redux";
import RentalSearchInput from "components/rental/RentalSearchInput";

class Header extends React.Component {
  constructor() {
    super();

    this.handleLogout = this.handleLogout.bind(this);
  }

  handleLogout() {
    this.props.logout();
    this.props.history.push("/rentals");
  }

  renderAuthButtons(isAuth) {
    if (isAuth) {
      return (
        <a className="nav-item nav-link clickable" onClick={this.handleLogout}>
          Logout
        </a>
      );
    }

    return (
      <React.Fragment>
        <Link className="nav-item nav-link" to="/login">
          Login <span className="sr-only">(current)</span>
        </Link>
        <Link className="nav-item nav-link" to="/register">
          Register
        </Link>
      </React.Fragment>
    );
  }

  renderOwnerSection(isAuth) {
    if (isAuth) {
      return (
        <div className="nav-item dropdown">
          <a
            className="nav-link nav-item dropdown-toggle clickable"
            id="navbarDropdownMenuLink"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            Owner Section
          </a>
          <div
            className="dropdown-menu"
            aria-labelledby="navbarDropdownMenuLink"
          >
            <Link className="dropdown-item" to="/rentals/new">
              Create Rental
            </Link>
            <Link className="dropdown-item" to="/rentals/manage">
              Manage Rentals
            </Link>
            <Link className="dropdown-item" to="/bookings/manage">
              Manage Bookings
            </Link>
          </div>
        </div>
      );
    }
  }

  render() {
    const { username, isAuth } = this.props.auth;

    return (
      <nav className="navbar navbar-dark navbar-expand-lg">
        <div className="container">
          <Link className="navbar-brand" to="/rentals">
            BookWithMe
            <img src={process.env.PUBLIC_URL + "/img/react-logo.svg"} alt="" />
          </Link>
          <RentalSearchInput />
          <button
            className="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div className="navbar-nav ml-auto">
              {isAuth && <a className="nav-item nav-link">{username}</a>}
              {this.renderOwnerSection(isAuth)}
              {this.renderAuthButtons(isAuth)}
            </div>
          </div>
        </div>
      </nav>
    );
  }
}

function mapStateToProps(state) {
  return {
    auth: state.auth,
  };
}

export default withRouter(connect(mapStateToProps)(Header));
