// GIT-USERS/Jerga/bwm-ng-new/src/app/shared/rental-card/rental-card.component.ts
import { Component, Input } from "@angular/core";
import { Rental } from "src/app/rental/shared/rental.model";

@Component({
  selector: "bwm-rental-card",
  templateUrl: "./rental-card.component.html",
  styleUrls: ["./rental-card.component.scss"],
})
export class RentalCardComponent {
  @Input("rentalItem") set rentalItem(rental: Rental) {
    this.rental = rental;
  }

  rental: Rental;
}

<div class="card bwm-card">
  <a routerLink="/rentals/{{ rental._id }}">
    <img class="card-img-top" [src]="rental.image?.url" alt="" />
    <div class="card-block">
      <h6 class="card-subtitle type-{{ rental.category }}">
        {{ rental.shared ? "Shared" : "Whole" }} {{ rental.category }} &#183;
        {{ rental.city }}
      </h6>
      <h4 class="card-title">{{ rental.title }}</h4>
      <p class="card-text">
        ${{ rental.dailyPrice }} per Night &#183; Free Cancelation
      </p>
    </div>
  </a>
  <ng-content></ng-content>
</div>

// GIT-USERS/Jerga/book-with-me-react/src/components/rental/rental-listing/RentalCard.js
import React from "react";
import { Link } from "react-router-dom";
import { resolveType } from "helpers";

export function RentalCard(props) {
  const rental = props.rental;

  return (
    <div className={props.colClass}>
      <Link to={`/rentals/${rental._id}`}>
        <div className="card bwm-card">
          <img className="card-img-top" src={rental.image} alt=""></img>
          <div className="card-block">
            <h6 className={`card-subtitle rental-type ${rental.category}`}>
              {resolveType(rental.shared)} {rental.category} &#183;{" "}
              {rental.city}
            </h6>
            <h4 className="card-title">{rental.title}</h4>
            <p className="card-text">
              ${rental.dailyRate} per Night &#183; Free Cancelation
            </p>
          </div>
        </div>
      </Link>
    </div>
  );
}
