// GIT-USERS/Jerga/bwm-react/src/components/shared/Header.js
import React from "react";
import { Link, withRouter } from "react-router-dom";
import { connect } from "react-redux";
import RentalSearchInput from "components/rental/RentalSearchInput";

class Header extends React.Component {
  constructor() {
    super();

    this.handleLogout = this.handleLogout.bind(this);
  }

  handleLogout() {
    this.props.logout();
    this.props.history.push("/rentals");
  }

  renderAuthButtons(isAuth) {
    if (isAuth) {
      return (
        <a className="nav-item nav-link clickable" onClick={this.handleLogout}>
          Logout
        </a>
      );
    }

    return (
      <React.Fragment>
        <Link className="nav-item nav-link" to="/login">
          Login <span className="sr-only">(current)</span>
        </Link>
        <Link className="nav-item nav-link" to="/register">
          Register
        </Link>
      </React.Fragment>
    );
  }

  renderOwnerSection(isAuth) {
    if (isAuth) {
      return (
        <div className="nav-item dropdown">
          <a
            className="nav-link nav-item dropdown-toggle clickable"
            id="navbarDropdownMenuLink"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            Owner Section
          </a>
          <div
            className="dropdown-menu"
            aria-labelledby="navbarDropdownMenuLink"
          >
            <Link className="dropdown-item" to="/rentals/new">
              Create Rental
            </Link>
            <Link className="dropdown-item" to="/rentals/manage">
              Manage Rentals
            </Link>
            <Link className="dropdown-item" to="/bookings/manage">
              Manage Bookings
            </Link>
          </div>
        </div>
      );
    }
  }

  render() {
    const { username, isAuth } = this.props.auth;

    return (
      <nav className="navbar navbar-dark navbar-expand-lg">
        <div className="container">
          <Link className="navbar-brand" to="/rentals">
            BookWithMe
            <img src={process.env.PUBLIC_URL + "/img/react-logo.svg"} alt="" />
          </Link>
          <RentalSearchInput />
          <button
            className="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div className="navbar-nav ml-auto">
              {isAuth && <a className="nav-item nav-link">{username}</a>}
              {this.renderOwnerSection(isAuth)}
              {this.renderAuthButtons(isAuth)}
            </div>
          </div>
        </div>
      </nav>
    );
  }
}

function mapStateToProps(state) {
  return {
    auth: state.auth,
  };
}

export default withRouter(connect(mapStateToProps)(Header));

// GIT-USERS/Jerga/initialNgProject/src/app/common/header/header.component.ts
import { Component } from "@angular/core";
import { AuthService } from "../../auth/shared/auth.service";
import { Router } from "@angular/router";

@Component({
  selector: "bwm-header",
  templateUrl: "./header.component.html",
  styleUrls: ["./header.component.scss"],
})
export class HeaderComponent {
  constructor(public auth: AuthService, private router: Router) {}

  logout() {
    this.auth.logout();
    this.router.navigate(["/login"]);
  }

  search(city: string) {
    city
      ? this.router.navigate([`/rentals/${city}/homes`])
      : this.router.navigate(["/rentals"]);
  }
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" routerLink="/rentals"
    >BookWithMe <img src="favicon.ico" alt=""
  /></a>

  <div class="form-inline">
    <input
      #citySearch
      (keyup.enter)="search(citySearch.value)"
      class="form-control mr-sm-2 bwm-search"
      type="search"
      placeholder="Search"
      aria-label="Search"
    />
    <button
      (click)="search(citySearch.value)"
      class="btn btn-outline-success my-2 my-sm-0 btn-bwm-search"
      type="button"
    >
      Search
    </button>
  </div>

  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <ng-container *ngIf="!auth.isAuthenticated()">
        <li class="nav-item active">
          <a class="nav-link" routerLink="/login"
            >Login <span class="sr-only">(current)</span></a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLink="/register">Register</a>
        </li>
      </ng-container>
      <ng-container *ngIf="auth.isAuthenticated()">
        <li class="nav-item">
          <a class="nav-link"> {{ auth.getUsername() }}</a>
        </li>
        <div class="nav-item dropdown clickable">
          <a
            class="nav-link dropdown-toggle"
            id="navbarDropdownMenuLink"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            Owner Section
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" routerLink="/rentals/new">Create Rental</a>
            <a class="dropdown-item" routerLink="/manage/rentals"
              >Manage Rentals</a
            >
            <a class="dropdown-item" routerLink="/manage/bookings"
              >Manage Bookings</a
            >
          </div>
        </div>
        <li class="nav-item clickable">
          <a class="nav-link" (click)="logout()">Logout</a>
        </li>
      </ng-container>
    </ul>
  </div>
</nav>
