// GIT-USERS/Jerga/angular-basics/src/app/shared/modal/modal.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-modal',
  templateUrl: './modal.component.html',
  styleUrls: ['./modal.component.scss'],
})
export class ModalComponent implements OnInit {
  @Input() isOpen: boolean;
  @Output() onClose = new EventEmitter();

  constructor() {}

  ngOnInit(): void {}
}

<div *ngIf="isOpen" class="app-modal">
  <!-- Modal content -->
  <div class="app-modal-content">
    <span (click)="onClose.next()" class="close">&times;</span>
    <ng-content></ng-content>
  </div>
</div>

// GIT-USERS/Jerga/react-basics/src/components/shared/Modal.js
import React from "react";

const Modal = ({ isOpen, onClose, children }) => {
  if (isOpen) {
    return (
      <div className="app-modal">
        <div className="app-modal-content">
          <span onClick={onClose} className="close">
            &times;
          </span>
          <div>{children}</div>
        </div>
      </div>
    );
  }

  return <></>;
};

export default Modal;
