// GIT-USERS/Jerga/bwm-react-new/src/components/rental/RentalCard.js
import React from "react";
import { Link } from "react-router-dom";

const RentalCard = ({ rental, renderMenu }) => {
  return (
    <>
      <Link className="rental-link" to={`/rentals/${rental._id}`}>
        <div className="card bwm-card">
          <img
            className="card-img-top"
            src={rental.image.url}
            alt={rental.title}
          />
          <div className="card-body">
            <h6 className={`card-subtitle mb-0 type-${rental.category}`}>
              {rental.shared ? "Shared" : "Whole"} {rental.category} &#183;{" "}
              {rental.city}
            </h6>
            <h5 className="card-title big-font">{rental.title}</h5>
            <p className="card-text">
              ${rental.dailyPrice} per Night &#183; Free Cancelation
            </p>
          </div>
        </div>
      </Link>
      {renderMenu && renderMenu()}
    </>
  );
};

export default RentalCard;

// GIT-USERS/Jerga/bwm-ng-new/src/app/shared/rental-card/rental-card.component.ts
import { Component, Input } from "@angular/core";
import { Rental } from "src/app/rental/shared/rental.model";

@Component({
  selector: "bwm-rental-card",
  templateUrl: "./rental-card.component.html",
  styleUrls: ["./rental-card.component.scss"],
})
export class RentalCardComponent {
  @Input("rentalItem") set rentalItem(rental: Rental) {
    this.rental = rental;
  }

  rental: Rental;
}

<div class="card bwm-card">
  <a routerLink="/rentals/{{ rental._id }}">
    <img class="card-img-top" [src]="rental.image?.url" alt="" />
    <div class="card-block">
      <h6 class="card-subtitle type-{{ rental.category }}">
        {{ rental.shared ? "Shared" : "Whole" }} {{ rental.category }} &#183;
        {{ rental.city }}
      </h6>
      <h4 class="card-title">{{ rental.title }}</h4>
      <p class="card-text">
        ${{ rental.dailyPrice }} per Night &#183; Free Cancelation
      </p>
    </div>
  </a>
  <ng-content></ng-content>
</div>
