// GIT-USERS/Jerga/khang-help/client/src/app/components/auth/login/login.component.ts
import { Component, OnInit } from "@angular/core";
import { FormBuilder, FormGroup, Validators } from "@angular/forms";
import { AuthService } from "../../../services/auth.service";
import { Router, ActivatedRoute } from "@angular/router";

@Component({
  selector: "app-login",
  templateUrl: "./login.component.html",
  styleUrls: ["./login.component.scss"],
})
export class LoginComponent implements OnInit {
  loginForm: FormGroup;
  errors: any = [];
  notifyMessage: string = "";

  constructor(
    private fb: FormBuilder,
    private auth: AuthService,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  ngOnInit() {
    this.initForm();

    this.route.params.subscribe((params) => {
      if (params["registered"] === "success") {
        this.notifyMessage =
          "You have been successfuly registered, you can login now!";
      }
    });
  }

  initForm() {
    this.loginForm = this.fb.group({
      email: [
        "",
        [
          Validators.required,
          Validators.pattern(
            "^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:.[a-zA-Z0-9-]+)*$"
          ),
        ],
      ],
      password: ["", Validators.required],
    });
  }

  isInvalidForm(fieldName): boolean {
    return;
    this.loginForm.controls[fieldName].invalid &&
      (this.loginForm.controls[fieldName].dirty ||
        this.loginForm.controls[fieldName].touched);
  }

  isRequired(fieldName): boolean {
    return this.loginForm.controls[fieldName].errors.required;
  }

  isPattern(fieldName): boolean {
    return this.loginForm.controls[fieldName].errors.pattern;
  }

  login() {
    this.auth.login(this.loginForm.value).subscribe(
      (token) => {
        this.router.navigate(["rentals"]);
      },

      (errorResponse) => {
        console.log(errorResponse);
        this.errors = errorResponse.error.err;
      },

      () => {}
    );
  }
}

<section id="login">
  <div class="bwm-form">
    <div class="row">
      <div class="col-md-5">
        <h1>Login</h1>
        <div *ngIf="notifyMessage" class="alert alert-success">
          {{ notifyMessage }}
        </div>

        <form [formGroup]="loginForm" (ngSubmit)="login()">
          <div class="form-group">
            <label for="email">Email</label>
            <input
              type="email"
              class="form-control"
              id="email"
              formControlName="email"
            />
            <div *ngIf="isInvalidForm('email')" class="alert alert-danger">
              <div *ngIf="isRequired('email')">Email is required.</div>
              <div *ngIf="isPattern('email')">Must be valid email format!</div>
            </div>
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input
              type="password"
              class="form-control"
              id="password"
              formControlName="password"
            />
          </div>
          <button
            type="submit"
            class="btn btn-bwm"
            mat-stroked-button
            [disabled]="!loginForm.valid"
          >
            Submit
          </button>
          <br />
          <br />
          <div *ngIf="errors.length > 0" class="alert alert-danger">
            <a *ngFor="let error of errors"> {{ error.detail }} </a>
          </div>
        </form>
      </div>
      <div class="col-md-6 ml-auto">
        <div class="image-container">
          <h2 class="catchphrase">
            Hundreds of awesome places in reach of few clicks.
          </h2>
          <img src="assets/images/login-image.jpg" alt="" />
        </div>
      </div>
    </div>
  </div>
</section>

// GIT-USERS/Jerga/bwm-react/src/components/login/Login.js
import React from "react";
import LoginForm from "./LoginForm";
import { connect } from "react-redux";
import { Redirect } from "react-router-dom";
import * as actions from "actions";

class Login extends React.Component {
  constructor() {
    super();

    this.loginUser = this.loginUser.bind(this);
  }

  loginUser(userData) {
    this.props.dispatch(actions.login(userData));
  }

  render() {
    const { isAuth, errors } = this.props.auth;
    const { successRegister } = this.props.location.state || false;

    if (isAuth) {
      return <Redirect to={{ pathname: "/rentals" }} />;
    }

    return (
      <section id="login">
        <div className="bwm-form">
          <div className="row">
            <div className="col-md-5">
              <h1>Login</h1>
              {successRegister && (
                <div className="alert alert-success">
                  <p>
                    {" "}
                    You have been succesfuly registered, please login now.{" "}
                  </p>
                </div>
              )}
              <LoginForm submitCb={this.loginUser} errors={errors} />
            </div>
            <div className="col-md-6 ml-auto">
              <div className="image-container">
                <h2 className="catchphrase">
                  Hundreds of awesome places in reach of few clicks.
                </h2>
                <img
                  src={process.env.PUBLIC_URL + "/img/login-image.jpg"}
                  alt=""
                />
              </div>
            </div>
          </div>
        </div>
      </section>
    );
  }
}

function mapStateToProps(state) {
  return {
    auth: state.auth,
  };
}

export default connect(mapStateToProps)(Login);
