// GIT-USERS/Jerga/bwm-react-new/src/components/booking/BookingListing.js
import React from "react";
import { Link } from "react-router-dom";
import { capitalize, formatDate } from "helpers/functions";
import ApiErrors from "components/forms/ApiErrors";

const BookingListing = ({
  isFetching,
  errors,
  bookings,
  renderMenu,
  type,
  title = "Bookings",
}) => {
  return (
    <section className="booking-listing">
      <h1 className="page-title">{title}</h1>
      {!isFetching && bookings.length === 0 && (
        <p className="alert alert-warning">No bookings created :(</p>
      )}
      <ApiErrors errors={errors} />
      <div className="row">
        {bookings.map((booking) => (
          <div key={booking._id} className="col-md-4">
            <div className="card text-center">
              {type === "received" && (
                <div className="card-header">From: {booking.user.username}</div>
              )}
              <div className="card-block">
                <h4 className="card-title">
                  {booking.rental.title} - {capitalize(booking.rental.city)}{" "}
                </h4>
                <p className="card-text booking-days">
                  {formatDate(booking.startAt)} - {formatDate(booking.endAt)} |{" "}
                  {booking.nights} nights
                </p>
                <p className="card-text">
                  <span>Price: </span>{" "}
                  <span className="booking-price-value">${booking.price}</span>
                </p>
                <Link
                  to={{ pathname: `/rentals/${booking.rental._id}` }}
                  className="btn btn-bwm-main"
                >
                  Go to Rental
                </Link>
                {renderMenu && renderMenu(booking._id)}
              </div>
              <div className="card-footer text-muted">
                Created at {formatDate(booking.createdAt)}
              </div>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
};

export default BookingListing;

// GIT-USERS/Jerga/bwm-ng-new/src/app/manage/components/booking-listing/booking-listing.component.ts
import { Component, OnInit, Input } from "@angular/core";
import { Observable } from "rxjs";
import { Booking } from "src/app/booking/shared/booking.model";
import { BookingService } from "src/app/booking/shared/booking.service";

@Component({
  selector: "bwm-booking-listing",
  templateUrl: "./booking-listing.component.html",
  styleUrls: ["./booking-listing.component.scss"],
})
export class BookingListingComponent implements OnInit {
  @Input("title") title: string;
  @Input("getBookings") getBookings: () => Observable<Booking[]>;
  @Input("type") type: string;

  bookings: Booking[];

  constructor(private bookingService: BookingService) {}

  ngOnInit() {
    this.getBookings().subscribe((bookings) => (this.bookings = bookings));
  }

  deleteBooking(bookingId: string) {
    const canDelete = this.askForPermission();
    if (!canDelete) {
      return;
    }

    this.bookingService.deleteBooking(bookingId).subscribe(
      (_) => {
        const index = this.bookings.findIndex((b) => b._id === bookingId);
        this.bookings.splice(index, 1);

        alert("Booking has been deleted!");
      },
      (_) => alert("Booking cannot be deleted!")
    );
  }

  private askForPermission(): boolean {
    return window.confirm("Are you sure you want to delete booking?");
  }
}

<section id="userBookings">
  <h1 class="page-title">{{ title }}</h1>
  <div class="row">
    <ng-container *ngIf="bookings">
      <!-- Iterate bookings -->
      <div *ngFor="let booking of bookings" class="col-md-4">
        <div class="card text-center">
          <div *ngIf="type === 'received'" class="card-header">
            From: {{ booking.user.username }}
          </div>
          <div class="card-block">
            <ng-container>
              <h4 class="card-title">
                {{ booking.rental.title }} -
                {{ booking.rental.city | upper: "firstLetterUpper" }}
              </h4>
            </ng-container>
            <p class="card-text booking-days">
              {{ booking.startAt | timeFormat }} -
              {{ booking.endAt | timeFormat }} | {{ booking.nights }} nights
            </p>
            <p class="card-text">
              <span>Price: </span>
              <span class="booking-price-value">${{ booking.price }}</span>
            </p>
            <a
              [routerLink]="'/rentals/' + booking.rental._id"
              class="btn bwm-btn-main"
              >Go to Rental</a
            >
            <button
              *ngIf="type === 'all'"
              (click)="deleteBooking(booking._id)"
              class="ml-1 btn btn-danger"
            >
              Delete
            </button>
          </div>
          <div class="card-footer text-muted">
            Created at {{ booking.createdAt | timeFormat }}
          </div>
        </div>
      </div>
      <div *ngIf="bookings.length === 0" class="alert alert-warning">
        No bookings created :(
      </div>
    </ng-container>
  </div>
</section>
