// GIT-USERS/Jerga/book-with-me-ng/src/app/rental/rental-detail/rental-detail-info/rental-detail-info.component.ts
import { Component, OnInit, Input } from "@angular/core";
import { Rental } from "../../shared/rental.model";
import { HelperService } from "../../../shared/service/helper.service";

@Component({
  selector: "bwm-rental-detail-info",
  templateUrl: "./rental-detail-info.component.html",
  styleUrls: ["./rental-detail-info.component.scss"],
})
export class RentalDetailInfoComponent {
  @Input() public rental: Rental;

  constructor(public helper: HelperService) {}
}

<div class="rental">
  <h2 class="rental-type {{ rental.category }}">
    {{ helper.rentalType(rental.shared) }} {{ rental.category }}
  </h2>
  <div class="rental-owner">
    <img src="https://api.adorable.io/avatars/285/abott@adorable.png" alt="" />
    <span>{{ rental.user.email }}</span>
  </div>
  <h1 class="rental-title">{{ rental.title }}</h1>

  <h2 class="rental-city">{{ rental.city | ucwords }}</h2>
  <div class="rental-room-info">
    <span><i class="fa fa-building"></i>{{ rental.bedrooms }} bedrooms</span>
    <span><i class="fa fa-user"></i> {{ rental.bedrooms + 4 }} guests</span>
    <span><i class="fa fa-bed"></i> {{ rental.bedrooms + 2 }} beds</span>
  </div>
  <p class="rental-description">
    {{ rental.description }}
  </p>
  <hr />
  <div class="rental-assets">
    <h3 class="title">Assets</h3>
    <div class="row">
      <div class="col-md-6">
        <span><i class="fa fa-asterisk"></i> Cooling</span>
        <span><i class="fa fa-thermometer"></i> Heating</span>
        <span><i class="fa fa-location-arrow"></i> Iron</span>
      </div>
      <div class="col-md-6">
        <span><i class="fa fa-desktop"></i> Working area</span>
        <span><i class="fa fa-cube"></i> Washing machine</span>
        <span><i class="fa fa-cube"></i> Dishwasher</span>
      </div>
    </div>
  </div>
</div>

// GIT-USERS/Jerga/book-with-me-react/src/components/rental/rental-detail/RentalDetailInfo.js
import React from "react";
import { RentalAssets } from "./RentalAssets";
import { resolveType, toUpperCase } from "helpers";

export function RentalDetailInfo({ rental }) {
  return (
    <div className="rental">
      <h2 className={`rental-type ${rental.category}`}>
        {resolveType(rental.shared)} {rental.category}
      </h2>
      <div className="rental-owner">
        <img
          src="https://api.adorable.io/avatars/285/abott@adorable.png"
          alt="owner"
        />
        <span>{rental.user && rental.user.email}</span>
      </div>
      <h1 className="rental-title">{rental.title}</h1>
      <h2 className="rental-city">{toUpperCase(rental.city)}</h2>
      <div className="rental-room-info">
        <span>
          <i className="fa fa-building"></i>
          {rental.bedrooms} bedrooms
        </span>
        <span>
          <i className="fa fa-user"></i> {rental.bedrooms + 4} guests
        </span>
        <span>
          <i className="fa fa-bed"></i> {rental.bedrooms + 2} beds
        </span>
      </div>
      <p className="rental-description">{rental.description}</p>
      <hr></hr>
      <RentalAssets></RentalAssets>
    </div>
  );
}
