// GIT-USERS/Jerga/vue-basics/src/components/ResourceSearch.vue
<template>
  <form class="card p-2">
    <div class="input-group">
      <input
        @keyup="$emit('on-search', $event.target.value)"
        type="text"
        class="form-control"
        placeholder="Some title"
      />
    </div>
  </form>
</template>

<script>
export default {
  emits: ["on-search"],
};
</script>

// GIT-USERS/Jerga/angular-basics/src/app/resource/components/resource-search/resource-search.component.ts
import {
  Component,
  Output,
  EventEmitter,
  ViewChild,
  ElementRef,
  AfterViewInit,
} from '@angular/core';

import { fromEvent } from 'rxjs';
import { debounceTime } from 'rxjs/operators';

@Component({
  selector: 'app-resource-search',
  templateUrl: './resource-search.component.html',
  styleUrls: ['./resource-search.component.scss'],
})
export class ResourceSearchComponent implements AfterViewInit {
  @ViewChild('searchInput') input: ElementRef;

  @Output() onSearch = new EventEmitter<string>();

  ngAfterViewInit() {
    fromEvent(this.input.nativeElement, 'keyup')
      .pipe(debounceTime(200))
      .subscribe((e: any) => {
        this.onSearch.emit(e.target.value);
      });
  }
}

<form class="card p-2">
  <div class="input-group">
    <input
      #searchInput
      type="text"
      class="form-control"
      placeholder="Some title"
    />
  </div>
</form>
