// GIT-USERS/Jerga/khang-help/client/src/app/components/auth/register/register.component.ts
import { Component, OnInit } from "@angular/core";
import { AuthService } from "../../../services/auth.service";
import { Router } from "@angular/router";

@Component({
  selector: "app-register",
  templateUrl: "./register.component.html",
  styleUrls: ["./register.component.scss"],
})
export class RegisterComponent implements OnInit {
  formData: any = {};
  errors: any[] = [];

  constructor(private auth: AuthService, private router: Router) {}

  ngOnInit() {}

  register() {
    this.auth.register(this.formData).subscribe(
      () => {
        this.router.navigate(["login", { registered: "success" }]);
      },
      (error) => {
        this.errors = error.error.err;
      },
      () => {}
    );
  }
}

<section id="register">
  <div class="bwm-form">
    <div class="row">
      <div class="col-md-5">
        <h1 class="page-title">Register</h1>
        <form #registerForm="ngForm">
          <div class="form-group">
            <label for="username">Username</label>
            <input
              [(ngModel)]="formData.username"
              type="text"
              class="form-control"
              id="username"
              name="username"
              #username="ngModel"
              required
            />
          </div>

          <div
            *ngIf="username.invalid && (username.dirty || username.touched)"
            class="alert alert-danger"
          >
            <div *ngIf="username.errors.required">Username is required.</div>
          </div>

          <div class="form-group">
            <label for="email">Email</label>
            <input
              type="email"
              class="form-control"
              id="email"
              [(ngModel)]="formData.email"
              name="email"
              required
            />
          </div>

          <div class="form-group">
            <label for="password">Password</label>
            <input
              type="password"
              class="form-control"
              id="password"
              [(ngModel)]="formData.password"
              name="password"
              required
            />
          </div>

          <div class="form-group">
            <label for="passwordConfirmation">Confirm Password</label>
            <input
              type="password"
              class="form-control"
              id="passwordConfirmation"
              [(ngModel)]="formData.passwordConfirmation"
              name="passwordConfirmation"
              required
            />
          </div>
          <button
            type="submit"
            class="btn btn-bwm"
            (click)="register(registerForm)"
            [disabled]="!registerForm.form.valid"
            mat-stroked-button
          >
            Submit
          </button>
        </form>

        <div *ngIf="errors.length > 0" class="alert alert-danger">
          <a *ngFor="let error of errors"> {{ error.detail }} </a>
        </div>
      </div>
      <div class="col-md-6 ml-auto">
        <div class="image-container">
          <h2 class="catchphrase">
            As our member you have access to most awesome places in the world.
          </h2>
          <img src="assets/images/register-image.jpg" alt="" />
        </div>
      </div>
    </div>
  </div>
</section>

// GIT-USERS/Jerga/bwm-react/src/components/register/Register.js
import React from "react";
import RegisterForm from "./RegisterForm";
import { Redirect } from "react-router-dom";

import * as actions from "actions";

export class Register extends React.Component {
  constructor() {
    super();

    this.state = {
      errors: [],
      redirect: false,
    };

    this.registerUser = this.registerUser.bind(this);
  }

  registerUser(userData) {
    actions.register(userData).then(
      (registered) => this.setState({ redirect: true }),
      (errors) => this.setState({ errors })
    );
  }

  render() {
    const { errors, redirect } = this.state;

    if (redirect) {
      return (
        <Redirect
          to={{ pathname: "/login", state: { successRegister: true } }}
        />
      );
    }

    return (
      <section id="register">
        <div className="bwm-form">
          <div className="row">
            <div className="col-md-5">
              <h1>Register</h1>
              <RegisterForm submitCb={this.registerUser} errors={errors} />
            </div>
            <div className="col-md-6 ml-auto">
              <div className="image-container">
                <h2 className="catchphrase">
                  As our member you have access to most awesome places in the
                  world.
                </h2>
                <img
                  src={process.env.PUBLIC_URL + "/img/register-image.jpg"}
                  alt=""
                />
              </div>
            </div>
          </div>
        </div>
      </section>
    );
  }
}
