// GIT-USERS/Jerga/bwm-ng-new/src/app/shared/header/header.component.ts
import { Component, Input } from "@angular/core";
import { Router } from "@angular/router";

@Component({
  selector: "bwm-header",
  templateUrl: "./header.component.html",
  styleUrls: ["./header.component.scss"],
})
export class HeaderComponent {
  @Input("isAuthenticated") isAuthenticated = false;
  @Input("username") username = "";
  @Input("logout") logout = () => {};

  constructor(private router: Router) {}

  search(city: string) {
    city
      ? this.router.navigate([`/rentals/${city}/homes`])
      : this.router.navigate(["/rentals"]);
  }
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" routerLink="/">BookWithMe</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="form-inline my-2 my-lg-0 mr-auto">
      <input
        #citySearch
        (keyup.enter)="search(citySearch.value)"
        class="form-control mr-sm-2 bwm-search"
        type="search"
        placeholder="Search"
        aria-label="Search"
      />
      <button
        (click)="search(citySearch.value)"
        class="btn btn-outline-success my-2 my-sm-0 bwm-btn-main"
      >
        Search
      </button>
    </div>
    <ul class="navbar-nav">
      <li *ngIf="isAuthenticated" class="nav-item active">
        <div class="nav-link">Hello {{ username }}!</div>
      </li>
      <li class="nav-item active">
        <a class="nav-link" routerLink="/"
          >Home <span class="sr-only">(current)</span></a
        >
      </li>
      <ng-container *ngIf="isAuthenticated; else notAuthMenu">
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            Manage
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" routerLink="/rentals/new">New Rental</a>
            <a class="dropdown-item" routerLink="manage/rentals">My Rentals</a>
            <a class="dropdown-item" routerLink="manage/bookings"
              >My Bookings</a
            >
            <a
              class="dropdown-item"
              [queryParams]="{ type: 'received' }"
              routerLink="manage/bookings"
              >Received Bookings</a
            >
          </div>
        </li>
        <li class="nav-item">
          <a (click)="logout()" class="nav-link">Logout</a>
        </li>
      </ng-container>
      <ng-template #notAuthMenu>
        <li class="nav-item">
          <a class="nav-link" routerLink="/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLink="/register">Register</a>
        </li>
      </ng-template>
    </ul>
  </div>
</nav>

// GIT-USERS/Jerga/bwm-new-react-github/src/components/shared/Header.js
/* eslint-disable jsx-a11y/anchor-is-valid */

import React from "react";
import { Link } from "react-router-dom";
import { connect } from "react-redux";

const Header = ({ username, isAuth, logout }) => {
  return (
    <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
      <Link className="navbar-brand" to="/">
        BookWithMe
      </Link>
      <button
        className="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span className="navbar-toggler-icon"></span>
      </button>

      <div className="collapse navbar-collapse" id="navbarSupportedContent">
        <form className="form-inline my-2 my-lg-0">
          <input
            className="form-control mr-sm-2 bwm-search"
            type="search"
            placeholder="Search"
            aria-label="Search"
          />
          <button
            className="btn btn-bwm-main btn-outline-success my-2 my-sm-0"
            type="submit"
          >
            Search
          </button>
        </form>
        <ul className="navbar-nav ml-auto">
          {isAuth && (
            <li className="nav-item">
              <div className="nav-link">Welcome {username}</div>
            </li>
          )}
          <li className="nav-item active">
            <Link className="nav-link" to="/">
              Home
              <span className="sr-only">(current)</span>
            </Link>
          </li>
          {isAuth && (
            <>
              <li className="nav-item dropdown">
                <a
                  className="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  Manage
                </a>
                <div className="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a className="dropdown-item" href="#">
                    Action
                  </a>
                  <a className="dropdown-item" href="#">
                    Another action
                  </a>
                  <div className="dropdown-divider"></div>
                  <a className="dropdown-item" href="#">
                    Something else here
                  </a>
                </div>
              </li>
              <li className="nav-item">
                <div onClick={logout} className="nav-link">
                  Logout
                </div>
              </li>
            </>
          )}
          {!isAuth && (
            <>
              <li className="nav-item">
                <Link className="nav-link" to="/login">
                  Login
                </Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" to="/register">
                  Register
                </Link>
              </li>
            </>
          )}
        </ul>
      </div>
    </nav>
  );
};

const mapStateToProps = ({ auth: { username, isAuth } }) => {
  return {
    username,
    isAuth,
  };
};

export default connect(mapStateToProps)(Header);
