// GIT-USERS/Jerga/react-basics/src/pages/ResourceNew.js
import React from "react";
import ResourceForm from "../components/ResourceForm";
import { useHistory } from "react-router-dom";
import withAlert from "../hoc/withAlert";

import { createResourceApi } from "../actions";

const ResourceNew = ({ alert, displayAlert }) => {
  const router = useHistory();

  const createResource = async (resource) => {
    try {
      const { _id } = await createResourceApi(resource);
      router.push(`/resources/${_id}`);
    } catch (e) {
      displayAlert("error", e);
    }
  };

  return <ResourceForm onSubmit={createResource} alert={alert} />;
};

export default withAlert(ResourceNew);

// GIT-USERS/Jerga/vue-basics/src/pages/ResourceNew.vue
<template>
  <resource-form
    :alert="alert"
    :resource="resource"
    @on-form-submit="createResource"
  />
</template>

<script>
import ResourceForm from "@/components/ResourceForm";
import { createResourceApi } from "@/actions";
import alertMixin from "@/mixins/alert";
export default {
  components: { ResourceForm },
  data() {
    return {
      resource: { title: "", description: "", type: "video", link: "" },
    };
  },
  mixins: [alertMixin],
  beforeUnmount() {
    this.clearAlertTimeout();
  },
  methods: {
    async createResource(resource) {
      try {
        await createResourceApi(resource);
        // Todo: redirect to Detail page
        this.$router.push({ name: "resourceHomePage" });
      } catch (errorMessage) {
        this.setAlert("error", errorMessage);
      }
    },
  },
};
</script>
